language: go

install:
    go get -u github.com/spf13/hugo

script:
    make

after_success:
    - ssh-agent -s
    - echo $DEPLOY_KEY > deploy-key
    - chmod 600 deploy-key
    - ssh-add deploy-key
    - make deploy
