language: go

install:
    # - sudo apt-get install python3-pygments
    - sudo pip install pygments
    - which pygmentize
    - go get -u github.com/spf13/hugo

script:
    hugo

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    repo: cissoid/cissoid.github.io
    local_dir: public
    target_branch: master
