addons:
  apt:
    packages:
      - python-pygments

install:
    - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb"
    - ls -l
    - sudo apt install -f ./hugo_${HUGO_VERSION}_Linux-64bit.deb

script:
    hugo

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    repo: cissoid/cissoid.github.io
    local_dir: public
    target_branch: master
