---
PygmentsCodeFences: true
baseURL: "http://blog.wxh.me"
copyright: "cissoid"
# disqusShortname: "cissoid-blog"
editor: "vim"
enableEmoji: true
enableRobotsTXT: true
googleAnalytics: "UA-67524885-1"
hasCJKLanguage: true
languageCode: "zh-cn"
metaDataFormat: "yaml"
newContentEditor: "vim"
paginate: 5
# permalinks: {post: "/:year/:month/:slug/"}
theme: "minimalism"
title: "B-log"

menu:
    navbar:
        - Name: "Posts"
          URL: "/post/"
          Weight: 1
        - Name: "About"
          URL: "/about/"
          Weight: 2
---
