---
baseURL: "https://blog.wxh.me"
copyright: "cissoid"
disableHugoGeneratorInject: true
disqusShortname: "cissoid-blog"
editor: "vim"
enableEmoji: true
enableRobotsTXT: true
googleAnalytics: "UA-67524885-1"
hasCJKLanguage: true
languageCode: "zh-cn"
metaDataFormat: "yaml"
newContentEditor: "vim"
paginate: 10
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsStyle: "monokai"
theme: "minimalism"
title: "B-log"

# permalinks: {post: "/:year/:month/:slug/"}

params:
    Subtitle: "cissoid 的装逼日志"

menu:
    navbar:
        - Name: "Posts"
          URL: "/post/"
          Weight: 1
        - Name: "About"
          URL: "/about/"
          Weight: 2
---
