---

baseURL: "http://blog.wxh.me"
copyright: "cissoid"
editor: "vim"
enableEmoji: true
enableRobotsTXT: true
googleAnalytics: "UA-67524885-1"
hasCJKLanguage: true
languageCode: "en-us"
metaDataFormat: "yaml"
newContentEditor: "vim"
paginate: 5
permalinks:
    post: /:year/:month/:title/
PygmentsCodeFences: true
title: "B-log"

theme: "hugo-theme-minimalism"

params:

---
